const data = [
  {
    title: 'Lake Inniscarra, Ireland — Pyramid',
    imgUrl: 'lake-inniscarra-ireland.jpg',
    avatarUrl: 'puspure_sanita_avatar_002.jpg',
    time: '30:53',
    distance: {
      value: '6,248',
      units: 'm',
    },
    moreUrl: 'https://ifit.com',
    workouts: []
  },
  {
    title: 'Performance Series',
    imgUrl: 'performance-series.jpg',
    avatarUrl: 'francia_susan_avatar_001.jpg',
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ]
  },
  {
    title: 'Slow Pulls and Fast Intervals',
    imgUrl: 'slow-pulls-fast-intervals.jpg',
    avatarUrl: 'alex_silver_fagan.jpg',
    time: '44:13',
    distance: {
      value: '9,948',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: '20 Minutes to Toned',
    imgUrl: '20-minutes-to-toned.jpg',
    avatarUrl: 'gregory_alex_avatar_01.jpg',
    time: '',
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    title: 'Charles Race, Boston, Massachusetts',
    imgUrl: 'charles-race-boston.jpg',
    avatarUrl: 'whipple_mary_hero.jpg',
    time: '36:22',
    distance: {
      value: '8,868',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: 'Full-Body HIIT Series',
    imgUrl: 'full-body-hiit.jpg',
    avatarUrl: 'eden_hannah_avatar_03.jpg',
    time: '',
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    title: 'Kafue River, Zambia — Power Stroke Pyramid',
    imgUrl: 'kafue-river-zambia-power-stroke-pyramid.jpg',
    avatarUrl: 'nanchengwa_desmond_avatar_003.jpg',
    time: '22:22',
    distance: {
      value: '4,660',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: 'Shred & Burn Series',
    imgUrl: 'shred-and-burn-series.jpg',
    avatarUrl: 'gideon_akande.jpg',
    time: '',
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
];

export default data;
