const data = [
  {
    title: 'Lake Inniscarra, Ireland — Pyramid',
    imgUrl: 'lake-inniscarra-ireland.jpg',
    avatarUrl: '',
    time: '30:53',
    distance: {
      value: '6,248',
      units: 'm',
    },
    moreUrl: 'https://ifit.com',
    workouts: []
  },
  {
    title: 'Performance Series',
    imgUrl: '',
    avatarUrl: '',
    time: '',
    distance: '',
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ]
  },
  {
    title: 'Slow Pulls and Fast Intervals',
    imgUrl: '',
    avatarUrl: '',
    time: '44:13',
    distance: {
      value: '9,948',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: '20 Minutes to Toned',
    imgUrl: '',
    avatarUrl: '',
    time: '',
    distance: {
      value: '',
      units: '',
    },
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    title: 'Charles Race, Boston, Massachusetts',
    imgUrl: '',
    avatarUrl: '',
    time: '36:22',
    distance: {
      value: '8,868',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: 'Full-Body HIIT Series',
    imgUrl: '',
    avatarUrl: '',
    time: '',
    distance: {
      value: '',
      units: '',
    },
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
  {
    title: 'Kafue River, Zambia — Power Stroke Pyramid',
    imgUrl: '',
    avatarUrl: '',
    time: '22:22',
    distance: {
      value: '4,660',
      units: 'm',
    },
    moreUrl: '',
    workouts: [],
  },
  {
    title: 'Shred & Burn Series',
    imgUrl: '',
    avatarUrl: '',
    time: '',
    distance: {
      value: '',
      units: '',
    },
    moreUrl: '',
    workouts: [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
];

export default data;
